spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: false
        format_sql: false
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/test?socketTimeout=300000
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
    minimum-idle: 5
    maximum-pool-size: 10
    connection-timeout: 10000
    validation-timeout: 10000
    idle-timeout: 10000
    max-lifetime: 290000

server:
  tomcat:
    connection-timeout: 300000  # 5분
  shutdown: graceful
  servlet:
    session:
      timeout: 30m

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

http:
  front:
    host: http://localhost:3000

jwt:
  header: Authorization
  secret: a2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbXRva2FyaW10b2thcmltdG9rYXJpbQ==
  token-validity-in-seconds: 3600000

gpt:
  key: t

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


logging:
  config: classpath:logback-local.xml
  level:
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql: off
    org.hibernate.type.descriptor.sql.BasicBinder: info
    org.hibernate.type.descriptor.sql.BasicExtractor: off
    io.awspring.cloud: trace
    com:
      doomole:
        portfolio: debug

api:
  naver:
    client-id: QJ27kn0CTDjEU5JbQcEJ
    client-secret: khUpIjjM8T
